CREATE TABLE IF NOT EXISTS `web_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `organization_id` int(11) NOT NULL DEFAULT 141,
  `session_id` varchar(100) NOT NULL,
  `visitor_id` varchar(100) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text,
  `device_type` enum('desktop','mobile','tablet','bot') NOT NULL DEFAULT 'desktop',
  `browser` varchar(50) DEFAULT NULL,
  `os` varchar(50) DEFAULT NULL,
  `language` varchar(10) DEFAULT 'de',
  `referrer` text,
  `utm_source` varchar(100) DEFAULT NULL,
  `utm_medium` varchar(100) DEFAULT NULL,
  `utm_campaign` varchar(100) DEFAULT NULL,
  `utm_content` varchar(100) DEFAULT NULL,
  `utm_term` varchar(100) DEFAULT NULL,
  `landing_page` varchar(500) DEFAULT NULL,
  `exit_page` varchar(500) DEFAULT NULL,
  `is_returning` tinyint(1) DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_activity` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `session_duration` int(11) DEFAULT 0 COMMENT 'Длительность сессии в секундах',
  `total_sections` int(11) DEFAULT 0 COMMENT 'Количество посещенных разделов',
  `page_views` int(11) DEFAULT 1,
  `bounce` tinyint(1) DEFAULT 1 COMMENT 'Отказ (единственная страница)',
  `is_bot` tinyint(1) DEFAULT 0 COMMENT 'Является ли ботом',
  `screen_resolution` varchar(20) DEFAULT NULL,
  `source` varchar(50) DEFAULT 'direct',
  
  PRIMARY KEY (`id`),
  KEY `idx_session_id` (`session_id`),
  KEY `idx_visitor_id` (`visitor_id`),
  KEY `idx_organization` (`organization_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_device_type` (`device_type`),
  KEY `idx_is_bot` (`is_bot`),
  KEY `idx_last_activity` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;